//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/proteus/connectors/black23.yaml
// auto-generated by PinoutLogic.java based on config/boards/proteus/connectors/black35.yaml
// auto-generated by PinoutLogic.java based on config/boards/proteus/connectors/white35.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char * getBoardSpecificPinName(brain_pin_e brainPin) {
	switch(brainPin) {
		case Gpio::A0: return "Entree Analog 11";
		case Gpio::A1: return "Entree Analog 1";
		case Gpio::A2: return "Entree Analog 2";
		case Gpio::A3: return "Entree Analog 3";
		case Gpio::A4: return "Entree Analog 4";
		case Gpio::A5: return "Entree Analog 5";
		case Gpio::A6: return "Entree Analog 6";
		case Gpio::A8: return "Spare 3";
		case Gpio::A9: return "Spare 4";
		case Gpio::B0: return "Sonde Temperature 3";
		case Gpio::B1: return "Sonde Temperature 4";
		case Gpio::B4: return "Sortie Basse 8;
		case Gpio::B5: return "Sortie Basse 7";
		case Gpio::B6: return "Sortie Basse 6";
		case Gpio::B7: return "Sortie Basse 5";
		case Gpio::B8: return "Sortie Basse 4";
		case Gpio::B9: return "Sortie Basse 3";
		case Gpio::C0: return "Entree Analog 7";
		case Gpio::C1: return "Entree Analog 8";
		case Gpio::C2: return "Entree Analog 9";
		case Gpio::C3: return "Entree Analog 10";
		case Gpio::C4: return "Sonde Temperature 1";
		case Gpio::C5: return "Sonde Temperature 2";
		case Gpio::C6: return "Digital 6";
		case Gpio::C7: return "Allumage 8";
		case Gpio::C8: return "Allumage 9";
		case Gpio::C9: return "Allumage 10";
		case Gpio::D10: return "ETB 1 DIR";
		case Gpio::D11: return "ETB 1 DIS";
		case Gpio::D12: return "ETB 1 PWM";
		case Gpio::D13: return "ETB 2 PWM";
		case Gpio::D14: return "Spare 1";
		case Gpio::D15: return "Spare 2";
		case Gpio::D3: return "Allumage 11";
		case Gpio::D4: return "Allumage 12";
		case Gpio::D7: return "Sortie Basse HC 3";
		case Gpio::D8: return "ETB 2 DIS";
		case Gpio::D9: return "ETB 2 DIR";
		case Gpio::E0: return "Sortie Basse 2";
		case Gpio::E1: return "Sortie Basse 1";
		case Gpio::E11: return "Digital 1";
		case Gpio::E12: return "Digital 2";
		case Gpio::E13: return "Digital 3";
		case Gpio::E14: return "Digital 4";
		case Gpio::E15: return "Digital 5";
		case Gpio::E2: return "Sortie Basse HC 4";
		case Gpio::E7: return "Spare Digital 1";
		case Gpio::E8: return "Spare Digital 1";
		case Gpio::G10: return "Sortie Basse HC 1";
		case Gpio::G11: return "Sortie Basse 12";
		case Gpio::G12: return "Sortie Basse 11";
		case Gpio::G13: return "Sortie Basse 10";
		case Gpio::G14: return "Sortie Basse 9";
		case Gpio::G2: return "Allumage 1";
		case Gpio::G3: return "Allumage 2";
		case Gpio::G4: return "Allumage 3";
		case Gpio::G5: return "Allumage 4";
		case Gpio::G6: return "Allumage 5";
		case Gpio::G7: return "Allumage 6";
		case Gpio::G8: return "Allumage 7";
		case Gpio::G9: return "Sortie Basse HC 2";
		default: return nullptr;
	}
	return nullptr;
}
