//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmare.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char * getBoardSpecificPinName(brain_pin_e brainPin) {
	switch(brainPin) {
		case Gpio::A8: return "Sortie Clim (A8)";
		case Gpio::A9: return "Ventilation Reservoir (A9)";
		case Gpio::B4: return "Non Cable 8 (B4)";
		case Gpio::B5: return "Non Cable 7 (B5)";
		case Gpio::B6: return "Inecteur Cyl 1 (B6)";
		case Gpio::B7: return "Inecteur Cyl 2 (B7)";
		case Gpio::B8: return "Inecteur Cyl 3 (B8)";
		case Gpio::B9: return "Inecteur Cyl 4 (B9)";
		case Gpio::C6: return "Flex (C6)";
		case Gpio::C7: return "Non Cable 2 (C7)";
		case Gpio::C8: return "Non Cable 3 (C8)";
		case Gpio::C9: return "Non Cable 4 (C9)";
		case Gpio::D10: return "DBW 1 Direction (D10)";
		case Gpio::D11: return "DBW 1 Disable (D11)";
		case Gpio::D12: return "DBW 1 Control (D12)";
		case Gpio::D14: return "Flap Echap (D14)";
		case Gpio::D15: return "Compteur (D15)";
		case Gpio::D3: return "Non Cable 5 (D3)";
		case Gpio::D4: return "Non Cable 6 (D4)";
		case Gpio::D7: return "IDLE1 (D7)";
		case Gpio::E0: return "Inecteur Cyl 5 (E0)";
		case Gpio::E1: return "Inecteur Cyl 6 (E1)";
		case Gpio::E11: return "PMH (E11)";
		case Gpio::E12: return "CAM Admi (E12)";
		case Gpio::E13: return "CAM Echap (E13)";
		case Gpio::E14: return "VSS (E14)";
		case Gpio::E15: return "Embrayage (E15)";
		case Gpio::E2: return "IDLE2 (E2)";
		case Gpio::E7: return "Frein (E7)";
		case Gpio::E8: return "MFL (E8)";
		case Gpio::G10: return "VANOS Admi (G10)";
		case Gpio::G11: return "DISA (G11)";
		case Gpio::G12: return "Pompe Essence (G12)";
		case Gpio::G13: return "Ventilateur (G13)";
		case Gpio::G14: return "Thermostat (G14)";
		case Gpio::G2: return "Allumage Cyl 1 (G2)";
		case Gpio::G3: return "Allumage Cyl 4 (G3)";
		case Gpio::G4: return "Allumage Cyl 2 (G4)";
		case Gpio::G5: return "Allumage Cyl 5 (G5)";
		case Gpio::G6: return "Allumage Cyl 3 (G6)";
		case Gpio::G7: return "Allumage 6 (G7)";
		case Gpio::G8: return "Non Cable 1 (G8)";
		case Gpio::G9: return "VANOS Echap (G9)";
		default: return nullptr;
	}
	return nullptr;
}
