//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmare.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::G2, // Allumage Cyl 1 (G2)
	Gpio::G3, // Allumage Cyl 4 (G3)
	Gpio::G4, // Allumage Cyl 2 (G4)
	Gpio::G5, // Allumage Cyl 5 (G5)
	Gpio::G6, // Allumage Cyl 3 (G6)
	Gpio::G7, // Allumage 6 (G7)
	Gpio::G8, // Non Cable 1 (G8)
	Gpio::C7, // Non Cable 2 (C7)
	Gpio::C8, // Non Cable 3 (C8)
	Gpio::C9, // Non Cable 4 (C9)
	Gpio::D3, // Non Cable 5 (D3)
	Gpio::D4, // Non Cable 6 (D4)
	Gpio::E1, // Inecteur Cyl 6 (E1)
	Gpio::E0, // Inecteur Cyl 5 (E0)
	Gpio::B9, // Inecteur Cyl 4 (B9)
	Gpio::B8, // Inecteur Cyl 3 (B8)
	Gpio::B7, // Inecteur Cyl 2 (B7)
	Gpio::B6, // Inecteur Cyl 1 (B6)
	Gpio::B5, // Non Cable 7 (B5)
	Gpio::B4, // Non Cable 8 (B4)
	Gpio::G14, // Thermostat (G14)
	Gpio::G13, // Ventilateur (G13)
	Gpio::G12, // Pompe Essence (G12)
	Gpio::G11, // DISA (G11)
	Gpio::G10, // VANOS Admi (G10)
	Gpio::G9, // VANOS Echap (G9)
	Gpio::D7, // IDLE1 (D7)
	Gpio::E2, // IDLE2 (E2)
	Gpio::D14, // Flap Echap (D14)
	Gpio::D15, // Compteur (D15)
	Gpio::A8, // Sortie Clim (A8)
	Gpio::A9, // Ventilation Reservoir (A9)
	Gpio::D11, // DBW 1 Disable (D11)
	Gpio::D12, // DBW 1 Control (D12)
	Gpio::D10, // DBW 1 Direction (D10)
// "Allumage Cyl 1 (G2)",
// "Allumage Cyl 4 (G3)",
// "Allumage Cyl 2 (G4)",
// "Allumage Cyl 5 (G5)",
// "Allumage Cyl 3 (G6)",
// "Allumage 6 (G7)",
// "Non Cable 1 (G8)",
// "Non Cable 2 (C7)",
// "Non Cable 3 (C8)",
// "Non Cable 4 (C9)",
// "Non Cable 5 (D3)",
// "Non Cable 6 (D4)",
// "Inecteur Cyl 6 (E1)",
// "Inecteur Cyl 5 (E0)",
// "Inecteur Cyl 4 (B9)",
// "Inecteur Cyl 3 (B8)",
// "Inecteur Cyl 2 (B7)",
// "Inecteur Cyl 1 (B6)",
// "Non Cable 7 (B5)",
// "Non Cable 8 (B4)",
// "Thermostat (G14)",
// "Ventilateur (G13)",
// "Pompe Essence (G12)",
// "DISA (G11)",
// "VANOS Admi (G10)",
// "VANOS Echap (G9)",
// "IDLE1 (D7)",
// "IDLE2 (E2)",
// "Flap Echap (D14)",
// "Compteur (D15)",
// "Sortie Clim (A8)",
// "Ventilation Reservoir (A9)",
// "DBW 1 Disable (D11)",
// "DBW 1 Control (D12)",
// "DBW 1 Direction (D10)",
}
